---
title: "Synthpop workshop 1"
author: "David Henderson"
date: "15 June 2018"
output: 
  html_document:
    theme: spacelab
    toc: true
    toc_float: true
    code_folding: hide
    df_print: paged
---

```{r opts, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Pre-workshop prep

##Packages 

Load the package + others

```{r load_synthpop}
library(synthpop) #Must be loaded before tidyverse or dplyr::select is masked
library(tidyverse)
library(skimr)
```

##Look at the data

```{r data, results='asis'}
skim(SD2011) %>% skimr::kable()
```


##Pick my variables

?? `sex`, `smoke`, `income` and `age`

Just for fun... `r anicon::faa("smile", animate = "bounce", size = 3)`


#Practical 1

##Task 1 My first two syntheses

Create a subset dataframe 

```{r subset, results='asis'}
test1 <- 
  SD2011 %>% 
  select(c(sex, smoke, income, age))
skim(test1) %>% kable()
```

Potential probems for the synthesis? 

* `income` is not normally distributed
* The level of missing data in `income` is almost 16%




